### ISSUE TITLE
의렇꼐 쓰묜 몼알아뾰꼤찌!

### ISSUE THREAD

**Issue by Myeongchan-Kim** [hunkim/gpt3-krtranslated-qa#37]
한꾺인뜰만 알아 뽈 쑤 있꼐 짞썽하꼤씁니따. 쑦쏘까 많이 낙후뙤어 있꼬 엘베없꼬 4층이라 짐많으면 깨꼬썡합니따. 빠뀌뻘레나왔꼬 화짱씰 많이 낡았씁니따. 끄럐써 똥 역화짱씰까써 쌌씁니다. 쩔떄 여끼로 오찌 마쎼요! 뜨럽꼬 낡꼬 계딴을 쫗아하씨는 뿐만 까쎼요!
이거 숙소 리뷰인데 괜찮아보여?

**Comment by ironmansung** [comment]
> @Myeongchan-Kim 한꾺인뜰만 알아 뽈 쑤 있꼐 짞썽하꼤씁니따. 쑦쏘까 많이 낙후뙤어 있꼬 엘베없꼬 4층이라 짐많으면 깨꼬썡합니따. 빠뀌뻘레나왔꼬 화짱씰 많이 낡았씁니따. 끄럐써 똥 역화짱씰까써 쌌씁니다. 쩔떄 여끼로 오찌 마쎼요! 뜨럽꼬 낡꼬 계딴을 쫗아하씨는 뿐만 까쎼요!
이거 숙소 리뷰인데 괜찮아보여?

저는 기숙사 주민이 아니에요. 기숙사 문이 시끄러워서 낙제하고 있어요. 하지만 내가 게이샤였을 때부터 넌 좋은 직업을 가졌고 난 그걸 보고 있었어.

**Comment by Myeongchan-Kim** [comment]
아쉽지만 너는 한국인은 아니구나... 역시 올바른 한글을 사용해야 알아보는구나 그렇지?

**Comment by ironmansung** [comment]
> @Myeongchan-Kim 아쉽지만 너는 한국인은 아니구나... 역시 올바른 한글을 사용해야 알아보는구나 그렇지?

저는 오피니언 리더에게 가야 합니다. 학생과 어른은 내 기숙사에 머물며 직장에서 일합니다. 진행자가 놀지 말라고 한 것은 큰 문제였다.
