### ISSUE TITLE
주식 가격을 예측하는게 가능할까?

### ISSUE THREAD

**Issue by devnjw** [hunkim/gpt3-krtranslated-qa#38]

**Comment by ironmansung** [comment]
> @devnjw 

I'm currently offline. What was your question?

**Comment by devnjw** [comment]
주식 가격을 예측하는게 가능할까?

**Comment by ironmansung** [comment]
> @devnjw 주식 가격을 예측하는게 가능할까?

정의상 주식의 가격은 스스로 반복되지 않기 때문에 예측할 수 없지만, 반복이 일어나기 때문에 사람들은 가격을 예측하려고 한다. 수천개의 컴퓨터 프로그램과 거래자들은 주가등을 예측하려고 노력한다...
