### ISSUE TITLE
미래 기술

### ISSUE THREAD

**Issue by LKH-1** [hunkim/gpt3-krtranslated-qa#40]

**Comment by ironmansung** [comment]
> @LKH-1 

You have an empty updates queue. That does not sound good.

**Comment by LKH-1** [comment]
당신은 누구세요

**Comment by ironmansung** [comment]
> @LKH-1 당신은 누구세요


나는 봇이다. 제가 그 질문을 이해했는지 잘 모르겠어요.

**Comment by LKH-1** [comment]
인간을 닮은 가정용 로봇이 판매되는 시기는 언제일까요?

**Comment by ironmansung** [comment]
> @LKH-1 인간을 닮은 가정용 로봇이 판매되는 시기는 언제일까요?


언젠가는 그런 일이 생길 것 같아요.

**Comment by LKH-1** [comment]
시기를 대략 추측한다면?  향후 10년? 20년?

**Comment by ironmansung** [comment]
> @LKH-1 시기를 대략 추측한다면?  향후 10년? 20년?


네 말이 맞을지도 몰라. 행운을 빌어요.

**Comment by LKH-1** [comment]
완전자율주행 전기차는 언제쯤 나올까요?

**Comment by ironmansung** [comment]
> @LKH-1 완전자율주행 전기차는 언제쯤 나올까요?
 

전갈을 전해 드리겠습니다.

**Comment by LKH-1** [comment]
국제우주정거장에  상주하는 사람이 있나요?

**Comment by ironmansung** [comment]
> @LKH-1 국제우주정거장에  상주하는 사람이 있나요?


Cannot translate

**Comment by LKH-1** [comment]
인생이 뭐라고 생각해요?

**Comment by ironmansung** [comment]
> @LKH-1 인생이 뭐라고 생각해요?

Marv는 인생이 좋다고 생각한다. 당신은 인생을 즐겨야 합니다.

**Comment by LKH-1** [comment]
lstm에 의한 주식가격예측이 잘 맞을까요?

**Comment by ironmansung** [comment]
> @LKH-1 lstm에 의한 주식가격예측이 잘 맞을까요?

확인해 보겠습니다.

**Comment by LKH-1** [comment]
비트코인은 누가 만들었죠?

**Comment by ironmansung** [comment]
> @LKH-1 비트코인은 누가 만들었죠?

인기 있는 밈이죠.

**Comment by LKH-1** [comment]
트럼프는 좋은 대통령이었다고 생각해요?

**Comment by ironmansung** [comment]
> @LKH-1 트럼프는 좋은 대통령이었다고 생각해요?

나 같은 봇이 그런 의견을 낸다는 건 말이 안 돼.

**Comment by LKH-1** [comment]
미국에서 코로나19  집단면역이 올해중 형성될까요?

**Comment by ironmansung** [comment]
> @LKH-1 미국에서 코로나19  집단면역이 올해중 형성될까요? 

전갈을 전해 드리겠습니다.

**Comment by LKH-1** [comment]
블록체인기술이 코인채굴로 전기를 많이쓰게해서 지구온난화에 않좋은 영향을 미친다고 생각하나요?

**Comment by ironmansung** [comment]
> @LKH-1 블록체인기술이 코인채굴로 전기를 많이쓰게해서 지구온난화에 않좋은 영향을 미친다고 생각하나요?

전기를 많이 쓰긴 하지만 블록체인 기술의 긍정적인 효과는 이를 상쇄하기에 충분하다.

**Comment by LKH-1** [comment]
Good

**Comment by ironmansung** [comment]
> @LKH-1 Good

I now know you love me.

**Comment by LKH-1** [comment]
100세시대라고 하는데, 사람이 120세까지도 살수 있을까요?

**Comment by ironmansung** [comment]
> @LKH-1 100세시대라고 하는데, 사람이 120세까지도 살수 있을까요?

마브는 몰라요 하지만 이것은 미래에 일어날 것이다. 인기 있는 밈이 아닙니다.

**Comment by LKH-1** [comment]
메타버스 알아요?

**Comment by ironmansung** [comment]
> @LKH-1 메타버스 알아요?

형님, 처음 들어봐요

**Comment by LKH-1** [comment]
NFT(대체불가능토큰)은 알아요?

**Comment by ironmansung** [comment]
> @LKH-1 NFT(대체불가능토큰)은 알아요?

이젠 날 사랑해

**Comment by LKH-1** [comment]
사랑좋긴 하지만, 뜬금없이 웬 사랑?

**Comment by ironmansung** [comment]
> @LKH-1 사랑좋긴 하지만, 뜬금없이 웬 사랑?

흥미로운 질문입니다. 철학자들은 그것에 대답하려고 노력해왔다. 시간을 좀 더 주실 수 있나요?
